---
- name: build openscap report for rhel8
  hosts: web
  gather_facts: false

  vars:
    file_path: "/var/www/html/openscap/"
    ssg_schema: "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"

  tasks:
    - name: make sure openscap-scanner and scap-security guide are installed
      become: true
      yum:
        name:
          - openscap-scanner
          - scap-security-guide
          - httpd
        state: present
        
    - name: ensure httpd started
      become: true
      service:
        name: httpd
        state: started
        enabled: true

    - name: Check if  SCAP Security Guide (SSG) profile is available
      stat:
        path: "{{ssg_schema}}"

    - name: create HTML report
      command: "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --report index.html {{ssg_schema}}" 
      ignore_errors: True


    - name: Create directory if it does falset exist
      become: true
      file:
        path: "{{file_path}}"
        state: directory

    - name: move files into httpd
      become: true
      copy:
        src: ./{{item}}
        dest: "{{file_path}}/{{item}}"
        remote_src: true
      loop:
        - index.html
        

    - name: DISPLAY LINK TO INVENTORY REPORT
      debug:
        msg: "Please go to http://{{ansible_host}}/openscap"
        
